version: "3.8"

services:
  app:
    image: ${IMAGE_FULL_NAME}
    container_name: creatorhub-app

    environment:
      SPRING_PROFILES_ACTIVE: prod # application-prod.yml
      SPRING_SERVER_PORT: ${SPRING_SERVER_PORT}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      CALLBACK_RESIZE_SECRET: ${CALLBACK_RESIZE_SECRET}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      CORS_CLIENT_URL: ${CORS_CLIENT_URL}
      CLOUDFRONT_BASE: ${CLOUDFRONT_BASE}
    ports:
      - "8000:8000"
    networks:
      - creatorhub-network
    restart: unless-stopped

networks:
  creatorhub-network:
    external: true