server:
  port: 8000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org.springframework.web: debug
    com.creatorhub: debug

spring:
  config:
    import: application-local-secret.yml
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

jwt:
  access-token-exp-min: 60
  refresh-token-exp-days: 1

file:
  max:
    thumbnail-size: 1MB
    manuscript-size: 5MB

app:
  cookie:
    secure: false  # 로컬 개발환경(HTTP)에서는 false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      access: read-only
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99

seed:
  enabled:
    member: false
    creation: false
    episode: false
    creation-aggregate: false

