ALTER TABLE creation ADD COLUMN total_view_count INT NOT NULL DEFAULT 0;
ALTER TABLE creation ADD COLUMN total_like_count INT NOT NULL DEFAULT 0;
ALTER TABLE creation ADD COLUMN total_rating_sum INT NOT NULL DEFAULT 0;
ALTER TABLE creation ADD COLUMN total_rating_count INT NOT NULL DEFAULT 0;
ALTER TABLE creation ADD COLUMN total_rating_average DECIMAL(4,3) NOT NULL DEFAULT 0.000;
