ALTER TABLE creation ADD COLUMN total_view_count BIGINT NOT NULL DEFAULT 0;
ALTER TABLE creation ADD COLUMN total_like_count BIGINT NOT NULL DEFAULT 0;
ALTER TABLE creation ADD COLUMN total_rating_sum BIGINT NOT NULL DEFAULT 0;
ALTER TABLE creation ADD COLUMN total_rating_count BIGINT NOT NULL DEFAULT 0;
ALTER TABLE creation ADD COLUMN total_rating_average DECIMAL(4,3) NOT NULL DEFAULT 0.000;
